name: Build Specific Bicep File

on:
  push:  # Trigger on all branches
    branches:
      - '**'
  pull_request:  # Trigger on pull requests

jobs:
  build-bicep:
    name: Validate and Build Bicep File
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install Azure CLI and Bicep CLI
    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    # Create the output directory
    - name: Create Output Directory
      run: mkdir -p compiled-templates

    # Validate and Build the Specific Bicep File
    - name: Validate and Build infra/doakops-dev-exported-template.bicep
      run: |
        az bicep build --file infra/doakops-dev-exported-template.bicep --outdir compiled-templates

    # Preview Deployment Changes with What-If
    - name: Preview Deployment Changes
      run: |
        az deployment group what-if \
          --resource-group <dev-resource-group-name> \
          --template-file compiled-templates/doakops-dev-exported-template.json \
          --parameters staticSites_doakops_dev_name=<dev-static-site-name>