name: Deploy Resources to Azure

on:
  push:
    branches:
      - main  # Trigger deployment to dev on push to main
  workflow_dispatch:  # Allow manual trigger for prod deployment

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: develop 

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to Azure
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install Azure CLI and Bicep CLI
    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    # Deploy the Bicep file to Dev
    - name: Deploy Bicep File to Dev
      run: |
        az deployment group create \
          --resource-group doakops-dev \
          --template-file infra/doakops-dev-exported-template.bicep \
          --parameters staticSites_doakops_dev_name=doakops-dev

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-dev  # Ensure dev deployment completes first
    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_PROD_CREDENTIALS }}

    # Install Azure CLI and Bicep CLI
    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    # Deploy the Bicep file to Prod
    - name: Deploy Bicep File to Prod
      run: |
        az deployment group create \
          --resource-group doakops-prod \
          --template-file infra/doakops-prod-exported-template.bicep \
          --parameters staticSites_doakops_dev_name=doakops-prod