name: Deploy web app to Azure Static Web Apps

env:
  APP_LOCATION: "/site"
  OUTPUT_LOCATION: "public"

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    name: Build and Deploy to Dev
    environment: develop 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build And Deploy to Dev
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}

  build_and_deploy_prod:
    runs-on: ubuntu-latest
    name: Build and Deploy to Prod
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build And Deploy to Prod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
