name: Deploy Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: site/public
      - name: Deploy to Azure Static Web Apps (Dev)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: "upload"
          app_location: "/site"
          api_location: "api"
          output_location: "public"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: site/public
      - name: Deploy to Azure Static Web Apps (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/site"
          api_location: "api"
          output_location: "public"